### ISSUE TITLE
Prefix setting statement is the wrong way run

### ISSUE THREAD

**Issue by adamtemple** [terraform-google-modules/terraform-google-cloud-storage#74]
https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/f2f3d3c4699bac795c9ed9bbc110ec1b27db8486/main.tf#L18

This expressions seems to be the wrong way around possibly? If set to anything other an empty string it appends region into the prefix, which I would expect to be the behaviour if no prefix is set?

**Comment by morgante** [comment]
This is the intended design actually - what's your goal?

**Comment by galan** [comment]
Hi, catching up here. I don't want the region automatically added to the name. The prefix should be something user-provided and not something automatically (since the bucket-name is referenced in many other places that do not need to know the region nor is it desired to have it in the name). Example:

```
module "gcs_buckets" {
  source  = "terraform-google-modules/cloud-storage/google"
  version = "~> 1.7"
  project_id  = var.project_id
  location = var.region
  prefix = "company-prefix"
  names = ["first", "second"]
}
```
Then I expect the buckets `company-prefix-first` and `company-prefix-second`. IF the region should be added to the name I can image a boolean to enable this behaviour, but not the other way around. Currently I have to pass an empty string, which is counter-intuitive as user and forces me to repeat the prefix in the names list.
